### ISSUE TITLE
[8.0][BUG] project_billing_utils - You try to install module that depends on module. But the latter module is not available in your system.

### ISSUE THREAD

**Issue by rafaelbn** [OCA/project-reporting#11]
module: project_billing_utils
version: 8.0

**Steps to reproduce**
- we have a runbot critical error

```
2016-02-29 11:34:15     CRITICAL    server  openerp.service.server:942 preload_registries

Failed to initialize database `3142795-8-0-72c29c-all`.
Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3142795-8-0-72c29c/openerp/service/server.py", line 929, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3142795-8-0-72c29c/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3142795-8-0-72c29c/openerp/modules/loading.py", line 319, in load_modules
    modobj.button_install(cr, SUPERUSER_ID, ids)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3142795-8-0-72c29c/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3142795-8-0-72c29c/openerp/addons/base/module/module.py", line 414, in button_install
    self.state_update(cr, uid, ids, 'to install', ['uninstalled'], context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3142795-8-0-72c29c/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3142795-8-0-72c29c/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3142795-8-0-72c29c/openerp/addons/base/module/module.py", line 393, in state_update
    raise orm.except_orm(_('Error'), _("You try to install module '%s' that depends on module '%s'.\nBut the latter module is not available in your system.") % (module.name, dep.name,))
except_orm: ('Error', u"You try to install module 'project_billing_utils' that depends on module 'project_analytic_line_view'.\nBut the latter module is not available in your system.")
```

**Expected behavior**

to Have runbot green

cc @sbidoul @yvaucher @mdietrichc2c @dreispt

**Comment by rafaelbn** [comment]
Sorry, I didn't check https://github.com/OCA/project-reporting/blob/9.0/project_billing_utils/__openerp__.py#L38
